language: java
dist: trusty
sudo: false
git:
  depth: 1
cache:
  directories:
  - "$HOME/.m2"
install: true
matrix:
  include:
  - os: linux
    jdk: openjdk8
  - os: linux
    jdk: oraclejdk8
    after_success:
    - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" &&
      echo $GPG_SECRET_KEYS | base64 --decode | gpg --import &&
      echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust &&
      ./mvnw clean deploy --settings .travis/settings.xml -Ddeployment -Dmaven.test.skip=true
  - os: linux
    jdk: openjdk9
  - os: linux
    jdk: openjdk10
  - os: linux
    jdk: oraclejdk10
  - os: linux
    jdk: openjdk11
  - os: linux
    jdk: oraclejdk11
script:
- "./mvnw clean package -Dmaven.javadoc.skip=false"

